### ISSUE TITLE
android环境下如何运行的

### ISSUE THREAD

**Issue by robin-shine** [emptywalker/PurchasingPlatform#1]
这个项目在Android项目下运行了吗？我自己配置的项目，没有在demo里面改，然后浏览器已经运行成功了，涉及多个js文件。这个在Android下地址配置有了解吗？我Android上一直运行不成功

**Comment by emptywalker** [comment]
这个不好意思，因为我是iOS的，对Android的情况不太了解，这个项目我只在iOS和web上运行过，没有在Android上运行，不过按照正常的流程应该是OK的，  因为我运行iOS的时候 ，也是按照推荐方法去运行的，可以成功
